Description: S3 Buckets for SlackBud Images, displayable with Roku network only

Conditions:
  DeployWestRegionOnly: !Equals [!Ref "AWS::Region", "us-west-2"]

Resources:

  SlackBudImagesBucketWest:
    Condition: DeployWestRegionOnly
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "sr-infra-slackbud-images-us-west-2"
      AccessControl: 'PublicRead'
      CorsConfiguration:
        CorsRules:
        - AllowedOrigins: ['*']
          AllowedMethods: [GET]
      LifecycleConfiguration:
        Rules:
        - Id: DeleteObjectsAfter60DaysRule
          Status: Enabled
          ExpirationInDays: '60'
  SlackBudImagesBucketPolicyWest:
    Condition: DeployWestRegionOnly
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref SlackBudImagesBucketWest
      PolicyDocument:
        Statement:
          -
            Sid: GrantDevQAProdAccountsAccessWest
            Effect: Allow
            Action:
              - s3:Put*
              - s3:Get*
              - s3:List*
            Principal:
              AWS:
                - arn:aws:iam::638782101961:root
                - arn:aws:iam::181133766305:root
                - arn:aws:iam::886239521314:root
            Resource:
              - arn:aws:s3:::sr-infra-slackbud-images-us-west-2
              - arn:aws:s3:::sr-infra-slackbud-images-us-west-2/*
          -
            Sid: AllowGetInRokuNetworkWest
            Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Principal: '*'
            Resource:
              - arn:aws:s3:::sr-infra-slackbud-images-us-west-2
              - arn:aws:s3:::sr-infra-slackbud-images-us-west-2/*
            Condition:
              IpAddress:
                aws:SourceIp:
                  - 50.224.7.192/26
                  - 50.224.7.64/26
                  - 50.224.7.32/27
                  - 50.224.7.128/26
                  - 52.8.254.63/32
                  - 216.38.147.4/32
