Description: Template specifying the configuration for what runs only in us-east-1

Conditions:
    UsEast1Only: !Equals [!Ref "AWS::Region", 'us-east-1']

Resources:
  SearchIndexedS3Bucket:
    Type: "AWS::S3::Bucket"
    Condition: UsEast1Only
    DependsOn:
    - SearchIndexedNotificationQueue
    - SearchIndexedNotificationQueuePolicy
    DeletionPolicy: Retain
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Join ['-', [sr-search-indexed, !Ref "AWS::AccountId"]]
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 15
          Status: Enabled
      NotificationConfiguration:
        QueueConfigurations:
        - Event: "s3:ObjectCreated:*"
          Filter:
            S3Key:
              Rules:
              - Name: "suffix"
                Value: "_SUCCESS"
          Queue: !GetAtt SearchIndexedNotificationQueue.Arn

  SearchIndexedS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Condition: UsEast1Only
    DependsOn: SearchIndexedS3Bucket
    Properties:
      Bucket: !Ref SearchIndexedS3Bucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:List*
          - s3:Get*
          Effect: Allow
          Principal:
            AWS:
            - arn:aws:iam::181133766305:root
            - arn:aws:iam::638782101961:root
            - arn:aws:iam::886239521314:root
          Resource:
          - !Join ['', ['arn:aws:s3:::', !Ref SearchIndexedS3Bucket, /*]]
          - !Join ['', ['arn:aws:s3:::', !Ref SearchIndexedS3Bucket, '']]
          Sid: S3PolicySearchIndexedS3BucketPolicy20170222
        Version: '2012-10-17'

  SearchIndexedNotificationQueue:
    Type: "AWS::SQS::Queue"
    Condition: UsEast1Only
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Join ['-', [sr-search-indexed, notification-queue] ]
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SearchIndexedNotificationDlQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 3600

  SearchIndexedNotificationDlQueue:
    Type: "AWS::SQS::Queue"
    Condition: UsEast1Only
    Properties:
      MessageRetentionPeriod: 345600
      QueueName: !Join ['-', [sr-search-indexed, notification-dl-queue] ]
      VisibilityTimeout: 60

  SearchIndexedNotificationQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Condition: UsEast1Only
    DependsOn: SearchIndexedNotificationQueue
    Properties:
      PolicyDocument:
        Id: "GlobalQueuePolicy"
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - sqs:*
            Principal: '*'
            Resource:
            - '*'
      Queues:
      - !Ref SearchIndexedNotificationQueue

Outputs:
  SearchIndexedS3Bucket:
    Condition: UsEast1Only
    Description: Name of the S3 bucket where SearchIndexer writes the _SUCCESS files
    Value: !Ref SearchIndexedS3Bucket
    Export:
        Name: !Sub ${AWS::StackName}:SearchIndexedS3Bucket

  SearchIndexedNotificationQueue:
    Condition: UsEast1Only
    Description: SQS queue that notifies when SearchIndexer has completed a job
    Value: !Ref SearchIndexedNotificationQueue
    Export:
      Name: !Sub ${AWS::StackName}:SearchIndexedNotificationQueue
